### ISSUE TITLE
re rfc deep merging (fieldset) : allow merging, but not changing type

### ISSUE THREAD

**Issue by Nzen** [eno-lang/eno#10]
## Summary

Eno currently has an open rfc to avoid combining the entries of fieldsets when applying the deep copy operator on a set. I allege this throws out valuable functionality in the name of avoiding unexpected typecasting. We ought to honor deep copy to all merge elements, so long as doing so does not change the type..

## Rfc d0520ae

The rfc to avoid merging fieldsets does not present a case for why merging the entry lists of each is of no or negative value. Rather, it addresses problematic consequences of changing the datatype of eno elements, as parsed, when resolving the dependency graph represented by shallow and deep copy operators.

I affirm that doing so is unwelcome.

However, we depart over the utility of merging elements of the same datatype.

## Use case

I use an [eno file](https://github.com/Nzen/JarLauncher/blob/master/etc/config.eno#L20) to model the startup arguments for another program. This involves some fields and a list that I append to for each startup style. However, to accommodate the list, I'm obliged to use one with an inconsistent name, given that copying onto the surrounding section deeply or shallowly doesn't merge the list.

```
# desired result - - - - - -
## customer 1
vendor : mysql
arguments:
- --max-memory
- 500M
- --database
- geospatial-usa-ne
## customer 2
vendor : microsoft
arguments:
- --max-memory
- 500M
- --database
- geospatial-usa-sw

# current workaround - - -
common values :
- --max-memory
- 500M
## customer 1
vendor : mysql
arguments < common values
- --database
- geospatial-usa-ne
## customer 2
vendor : microsoft
arguments < common values
- --database
- geospatial-usa-sw

# desired syntax - - -
## base
vendor : mysql
arguments:
- --max-memory
- 500M
## customer 1 << base
arguments:
- --database
- geospatial-usa-ne
## customer 2 << base
vendor : microsoft
arguments:
- --database
- geospatial-usa-sw
```
The desired syntax is shorter than the workaround currently required. This example and the file I linked to are intentionally brief. The file I use at work has thirty or so sections and more fields that vary in value between them. Focusing exclusively on the differences is a savings in terms of typing and attention.

**Comment by simonrepp** [comment]
Hey again, thanks for the input!

I guess the crux here is that either way we're losing something, would you agree?
My original proposal sacrifices the possibility to deep-merge down into the terminal element level (which of course does have value as you clearly point out), whereas this sacrifices the possibility to override an element (eg. "null" it out with an empty) or change the type (which also has its applications, I'm frequently using this to represent some data either in a concise or a detailed fashion, depending on which is needed).

Let me know what you think, I'll let this sink in a bit meanwhile, thanks for bringing it up! :)

ps. technically I've already chosen to close the lid on this specific rfc decision (see https://eno-lang.org/eno/specification/finalization-process/), but I'm open to let this sink in just to see if this turns out to be a missed opportunity after all.

**Comment by Nzen** [comment]
You express a concern that this issue and rfc d0520ae are incompatible for the use cases outlined therein. I affirm that changing the parsed datatype as described is unwelcome, even if it is someone's potential use case. I recognize that we're speaking about distinct implementations, but I affirm that eno libraries ought to treat a field with no value as a distinct type from a list or fieldset.

In that mindset, would it be conscionable to expect eno parsing libaries to merge the sub elements of a deep copied section, provided it doesn't change the datatype of the element in the target ?

I recognize that you own or are indirectly responsible for the majority of the world's eno corpus. Likely, accommodating this isn't just the effort to change enolib and tree sitter grammars. I'm familiar with dreading an audit of a population of code out in the wild. Okay. If it's overwhelming, consider an alternative that permits merging but is backward compatible with existing documents:

Eno libraries that deserialize a deep copy section recognize a new operator, ex <>, that follows a non section name. This operator indicates the document author intends that queries of this element return the union of the (indirectly) referenced and marked element.

```
> an example of the fallback proposition

# base
union :
- ff

# child << base
union <>
- gg

> The <> symbol above serves as an indication that queries
> of child's copy of union should offer the below representation

> intended representation after parsing - -
# child
union:
- ff
- gg
```

**Comment by simonrepp** [comment]
Thanks for the clarifications!

Following your proposal (the first part), as I understand it, there would be no way to do these things:
```
# base
## container
config:
- first this
- second this

# derived << base
## container
> I want to specifically empty the config list here
config:

# derived << base
## container
> I want to specifically overwrite the config list here
config:
- this and only this
```
Even this for me is prohibitive for following up with the proposal (these seem to be rather basic things), but of course do feel free to correct me if I got this wrong!

Regarding the alternative approach with a new operator, this adds more complexity to eno as a whole and also especially to what is already the most complex piece in it in the first place, so given eno's aim for simplicity I have to straight away reject that, sorry!

On the actual usecase you added I'd like to add that I actually really like how you solved the issue - you might feel it is a workaround, but I feel this is actually very readable, clear and obvious! Verbosity might look unappaealing on the language design front sometimes, but it just as well often saves people a lot of trouble when it's spelled out more clearly what is actually happening in data and code, just to add yet another perspective to that matter. :)
