### ISSUE TITLE
re. rfc key || name: key implies uniqueness

### ISSUE THREAD

**Issue by Nzen** [eno-lang/eno#5]
The commit 1b41110 introduces an rfc to change the terminology used to describe the identifying text for elements. It proposes the use of _key_ rather than _name_.

I submit this change not propagate to the final spec. Key, as used in other software, generally implies a unique identifier, as in maps. However, Eno doesn't require the fields of sections to have unique identifiers. Instead it draws the distinction, as explained in the [advanced features](https://eno-lang.org/advanced/) of the language overview, between typical fields and fieldsets.

The use of _name_  for these identifiers better represents this feature.

**Comment by simonrepp** [comment]
Thanks for the input!

I see your point! For me personally `key` does not generally imply uniqueness, but if it does to you - if it does to someone - I will think about this some more.

In any case I'd also like to stress that the motivation for this RFC is that right now, `name` itself is already implying things it shouldn't - so do think of this also as "What implication is worse?". Right now I feel I'd rather imply `"eno does not support duplicate keys"` ((*), who wants that anyway :)) than `"eno does not support int/float/arbitrarily-typed keys"` (the APIs soon will). :)

(*) eno does in fact not have duplicate keys in the problematic sense of silently replacing a previous key's value when a duplicate key is found. Keys *are* unique, one just variably stores single or multiple things under one key.

**Comment by simonrepp** [comment]
Also let's keep an open eye for a possible option C, this does not necessarily have to be key vs. name, that's just what's most realistic right now! :)
