### ISSUE TITLE
Arrays

### ISSUE THREAD

**Issue by PierreMarchand20** [eno-lang/eno#7]
Is there a way to have an array of float values ? If yes, what is the best way to do so ?

It seems that the APIs cannot parse an array though, so is it something you are planning to do ?

**Comment by simonrepp** [comment]
There's of course this:

```eno
my_floats:
- 1.3
- 2.5
```

```python
# ...
>>> document.float_list('my_floats')
[1.3, 2.5]
```

... but I suppose you are aware of that (correct me if I'm wrong :)) and instead what you mean is if there is a more concise (e.g. inline) syntax?

In that case eno's approach is to allow whatever syntax is best for your usecase and handle it with a custom loader, e.g.:

```python
import enopy

document = enopy.parse('my_floats: 1.3, 2.5')

# Using a custom single-use lambda loader

document.field('my_floats', lambda value: [float(number) for number in value.split(',')])
# => [1.3, 2.5]

# Using a custom reusable loader function

def inline_floats(value):
  return [float(number) for number in value.split(',')]

document.field('my_floats', inline_floats)
# => [1.3, 2.5]
```
(I quickly tested that code so it should be good to copy and play around with as it is :))

Of course you can also use any other syntax, with brackets, other separators ... if you use a custom loader prominently it also makes sense to integrate some validation (see e.g. examples at https://eno-lang.org/python/section/field/)

The custom types and loaders that ship with the current libraries are by the way defined in that same way, just simple functions that validate and/or convert the string value to a different type.

As a sneakpeek, in the coming library releases I am currently working on I will expose a mechanism for dynamically registering custom types with the core API, allowing something like this (still working on python, so exact code might change):

```python
def foo(value):
  return f"{value} with extra foo"

enopy.register(foo)

document = parse('my_field: my value')

document.field('my_field').foo_value()
# => 'my value with extra foo'

# And then also possible ... 

document.field('my_field').foo_key()
# => 'my_field with extra foo'
```
Let me know if anything's unclear still! :)

**Comment by PierreMarchand20** [comment]
Perfect ! Looking forward for the new releases ;-)

**Comment by simonrepp** [comment]
Definitely want to include something more practical on the whole loader concept in the docs, been starting on reworking the website(s) and documentation there days, I'll keep this in mind!
